{{- include "helm-library.container-secret" (list . "aircraft-tracking.container-secret") -}}
{{- define "aircraft-tracking.container-secret" -}}
stringData:
  MESSAGE_USERNAME: {{ quote .Values.container.messageUsername }}
  MESSAGE_PASSWORD: {{ quote .Values.container.messagePassword }}
{{- end -}}
