{{- include "helm-library.deployment" (list . "aircraft-tracking.deployment") -}}
{{- define "aircraft-tracking.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "helm-library.container" (list . "aircraft-tracking.container") }}
{{- end -}}
