{{- include "helm-library.secret" (list . "aircraft-tracking.secret") -}}
{{- define "aircraft-tracking.secret" -}}
stringData:
  MESSAGE_USERNAME: {{ quote .Values.container.messageUsername }}
  MESSAGE_PASSWORD: {{ quote .Values.container.messagePassword }}
  API_USERNAME: {{ quote .Values.container.apiUsername }}
  API_PASSWORD: {{ quote .Values.container.apiPassword }}
{{- end -}}
