apiVersion: v2
name: aircraft-tracking
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
dependencies:
- name: helm-library
  version: ^2.6.2
  repository: https://helm.lynxmagnus.com
