environment: development
name: aircraft-tracking
image: aircraft-tracking

container:
  imagePullPolicy: Always
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  messageHost:
  messagePassword:
  messageExchange: aircraft-tracked

deployment:
  restartPolicy: Always
  replicas: 1
